function GraphemeColour(){var U='',Cb='" for "gwt:onLoadErrorFn"',Ab='" for "gwt:onPropertyErrorFn"',nb='"><\/script>',cb='#',Kb='&',yc='.cache.html',eb='/',qb='//',ac='115337ECBAE740750A2ED28768A5D981',cc='1CB4ADF544A31C8C7326D4FFC10CEC45',dc='24F8EBF7061C5F5C51C2FD067C1F0AF4',ec='30FB1BC7A58610084CC49A57EB2CA69C',fc='447561B58362E5E55F733626B2974B1E',gc='47E82341AE5BAEE3FD3C8ED9C3F9C8B8',ic='559193B03D0DE1E031CAEFE377B72391',kc='5B4553C384275EE000711D104E1BD3D3',lc='704B01AED66723F93F784BD1856A9DEE',mc='7A2D1B07771DE5643BF4773E5220F032',nc='84E5259DBC52148E1A1AE6D679D8B96A',oc='91BB5860E64ACDDD4C81B071B64959C0',pc='94813C2FA0BA6B0AB0EBD9B6E8A7250C',qc='94B6B1230D28A5363DF29F180AD6DDDE',xc=':',ub='::',Gc='<script defer="defer">GraphemeColour.onInjectionDone(\'GraphemeColour\')<\/script>',mb='<script id="',xb='=',db='?',rc='A12B80501EE825EACA237F7B7A872A25',sc='A3D0F83927C7B5BEF74E001A624F7C41',tc='B18F42D8AACBAD13485E4EE9E4EA8E9F',uc='BA992591D47A40D81EB9C28966ABEABD',vc='BB0C1652474893F08ED4BD61678E013A',zb='Bad handler "',Fc='DOMContentLoaded',wc='E0DBC1EFBC3A9B5A48766CCE57F195E9',V='GraphemeColour',jb='GraphemeColour.nocache.js',tb='GraphemeColour::',ob='SCRIPT',Nb='Unexpected exception in locale detection, using default: ',Mb='_',Lb='__gwt_Locale',lb='__gwt_marker_GraphemeColour',pb='base',hb='baseUrl',Y='begin',X='bootstrap',gb='clear.cache.gif',wb='content',_b='de',bc='default',Ib='en',bb='end',hc='fr',Vb='gecko',Wb='gecko1_8',Z='gwt.codesvr=',$='gwt.hosted=',_='gwt.hybrid',zc='gwt/standard/standard.css',Bb='gwt:onLoadErrorFn',yb='gwt:onPropertyErrorFn',vb='gwt:property',Ec='head',Zb='hosted.html?GraphemeColour',Dc='href',Sb='ie10',Ub='ie8',Tb='ie9',Db='iframe',fb='img',Eb="javascript:''",Ac='link',Yb='loadExternalRefs',Hb='locale',Jb='locale=',rb='meta',Gb='moduleRequested',ab='moduleStartup',Rb='msie',sb='name',jc='nl',Fb='position:absolute;width:0;height:0;border:none',Bc='rel',Qb='safari',ib='script',$b='selectingPermutation',W='startup',Cc='stylesheet',kb='undefined',Xb='unknown',Ob='user.agent',Pb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=U,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:Y});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Z)!=-1||(c.indexOf($)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(_)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(V);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return M(a)}}GraphemeColour=null;c.gwtOnLoad(C,V,t,B);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:bb})}}
function H(){function e(a){var b=a.lastIndexOf(cb);if(b==-1){b=a.length}var c=a.indexOf(db);if(c==-1){c=a.length}var d=a.lastIndexOf(eb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(fb);b.src=a+gb;a=e(b.src)}return a}
function g(){var a=K(hb);if(a!=null){return a}return U}
function h(){var a=n.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(jb)!=-1){return e(a[b].src)}}return U}
function i(){var a;if(typeof isBodyLoaded==kb||!isBodyLoaded()){var b=lb;var c;n.write(mb+b+nb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ob){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return U}
function j(){var a=n.getElementsByTagName(pb);if(a.length>0){return a[a.length-1].href}return U}
function k(){var a=n.location;return a.href==a.protocol+qb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==U){l=h()}if(l==U){l=i()}if(l==U){l=j()}if(l==U&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(rb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(sb),g;if(f){f=f.replace(tb,U);if(f.indexOf(ub)>=0){continue}if(f==vb){g=e.getAttribute(wb);if(g){var h,i=g.indexOf(xb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=U}u[f]=h}}else if(f==yb){g=e.getAttribute(wb);if(g){try{D=eval(g)}catch(a){alert(zb+g+Ab)}}}else if(f==Bb){g=e.getAttribute(wb);if(g){try{C=eval(g)}catch(a){alert(zb+g+Cb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function M(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var N;function O(){if(!N){N=true;var a=n.createElement(Db);a.src=Eb;a.id=V;a.style.cssText=Fb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:ab,millis:(new Date).getTime(),type:Gb});a.contentWindow.location.replace(t+Q)}}
w[Hb]=function(){var b=null;var c=Ib;try{if(!b){var d=location.search;var e=d.indexOf(Jb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Kb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=K(Hb)}if(!b){b=m[Lb]}if(b){c=b}while(b&&!J(Hb,b)){var h=b.lastIndexOf(Mb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Nb+a)}m[Lb]=c;return b||Ib};v[Hb]={de:0,'default':1,en:2,fr:3,nl:4};w[Ob]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Pb)!=-1}())return Qb;if(function(){return b.indexOf(Rb)!=-1&&n.documentMode>=10}())return Sb;if(function(){return b.indexOf(Rb)!=-1&&n.documentMode>=9}())return Tb;if(function(){return b.indexOf(Rb)!=-1&&n.documentMode>=8}())return Ub;if(function(){return b.indexOf(Vb)!=-1}())return Wb;return Xb};v[Ob]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};GraphemeColour.onScriptLoad=function(){if(N){r=true;G()}};GraphemeColour.onInjectionDone=function(){q=true;o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:Yb,millis:(new Date).getTime(),type:bb});G()};I();H();var P;var Q;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(V))){m.location.reload();return}Q=Zb;P=U}o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:$b});if(!F()){try{L([_b,Ub],ac);L([bc,Sb],cc);L([Ib,Sb],cc);L([_b,Sb],dc);L([_b,Wb],ec);L([_b,Tb],fc);L([bc,Qb],gc);L([Ib,Qb],gc);L([hc,Sb],ic);L([jc,Wb],kc);L([bc,Wb],lc);L([Ib,Wb],lc);L([jc,Ub],mc);L([jc,Tb],nc);L([bc,Tb],oc);L([Ib,Tb],oc);L([bc,Ub],pc);L([Ib,Ub],pc);L([hc,Wb],qc);L([hc,Tb],rc);L([hc,Qb],sc);L([hc,Ub],tc);L([_b,Qb],uc);L([jc,Qb],vc);L([jc,Sb],wc);P=A[M(Hb)][M(Ob)];var R=P.indexOf(xc);if(R!=-1){B=Number(P.substring(R+1));P=P.substring(0,R)}Q=P+yc}catch(a){return}}var S;function T(){if(!s){s=true;if(!__gwt_stylesLoaded[zc]){var a=n.createElement(Ac);__gwt_stylesLoaded[zc]=a;a.setAttribute(Bc,Cc);a.setAttribute(Dc,t+zc);n.getElementsByTagName(Ec)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Fc,T,false)}if(S){clearInterval(S)}}}
if(n.addEventListener){n.addEventListener(Fc,function(){O();T()},false)}var S=setInterval(function(){if(/loaded|complete/.test(n.readyState)){O();T()}},50);o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:X,millis:(new Date).getTime(),type:bb});o&&o({moduleName:V,sessionId:p,subSystem:W,evtGroup:Yb,millis:(new Date).getTime(),type:Y});n.write(Gc)}
GraphemeColour();