function GraphemeColour(){var Q='bootstrap',R='begin',S='gwt.codesvr.GraphemeColour=',T='gwt.codesvr=',U='GraphemeColour',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='GraphemeColour::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='GraphemeColour.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='en',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb=3,Wb='user.agent',Xb='webkit',Yb='safari',Zb='msie',$b=10,_b=11,ac='ie10',bc=9,cc='ie9',dc=8,ec='ie8',fc='gecko',gc='gecko1_8',hc=4,ic='selectingPermutation',jc='GraphemeColour.devmode.js',kc='0B64FA14B64085CF5BC95E9E9A8CBE3E',lc='1F28562B860947CA6E15CBF5C5B97237',mc='nl',nc='3238F0B2034D921A590D56A51B3186EA',oc='3E0B4CD4FEADEABB9E5FF68E5CA62C6A',pc='4F152FB29847BF43102E9CFBE95B4E78',qc='de',rc='522EF959F882E858F047B4E5CC2CEB09',sc='6C6FE3419124887D807E9095F2067582',tc='7E3ED034AAACA8F22C9E1BC83EB7531A',uc='8557B2481F95FEA513D30F865750BD57',vc='8B7B8B624B2DA95C16B95D02B88DF440',wc='default',xc='9769349F1A3404BE12377CDE34E4FEFC',yc='9D3D0529BB185DC9C9A160A76B3C9991',zc='A752AC176516CBB7EF5FB3A78C960D0F',Ac='C814B09B4DAEF4C4063AFA239090BAFD',Bc='CAB1A2D7D87DF78086F8DCB664061869',Cc='CBAAE4C893DAD174965BD0624BEE9E0A',Dc='D9BF11F506D5F024D0C5E0BBBDBDE0BD',Ec='DC37CD5AC2D46E48080F14BED4D23FA9',Fc='E5B54DCB1531C1B0A5C2F2D452AA1022',Gc='F92F47C62A8E52F40DFF38D88C2821F7',Hc=':',Ic='.cache.js',Jc='link',Kc='rel',Lc='stylesheet',Mc='href',Nc='loadExternalRefs',Oc='gwt/standard/standard.css',Pc='end',Qc='http:',Rc='file:',Sc='_gwt_dummy_',Tc='__gwtDevModeHook:GraphemeColour',Uc='Ignoring non-whitelisted Dev Mode URL: ',Vc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
GraphemeColour.__sendStats=t;GraphemeColour.__moduleName=U;GraphemeColour.__errFn=null;GraphemeColour.__moduleBase=W;GraphemeColour.__softPermutationId=X;GraphemeColour.__computePropValue=null;GraphemeColour.__getPropMap=null;GraphemeColour.__installRunAsyncCode=function(){};GraphemeColour.__gwtStartLoadingFragment=function(){return null};GraphemeColour.__gwt_isKnownPropertyValue=function(){return false};GraphemeColour.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};GraphemeColour.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[GraphemeColour.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
GraphemeColour.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(GraphemeColour.__errFn){n.onerror=function(){GraphemeColour.__errFn(U,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
GraphemeColour.__startLoadingFragment=function(a){return G(a)};GraphemeColour.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,db);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;GraphemeColour.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return GraphemeColour.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={de:X,'default':Y,en:Ub,nl:Vb};m[Wb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Xb)!=-1}())return Yb;if(function(){return a.indexOf(Zb)!=-1&&(b>=$b&&b<_b)}())return ac;if(function(){return a.indexOf(Zb)!=-1&&(b>=bc&&b<_b)}())return cc;if(function(){return a.indexOf(Zb)!=-1&&(b>=dc&&b<_b)}())return ec;if(function(){return a.indexOf(fc)!=-1||b>=_b}())return gc;return db};l[Wb]={gecko1_8:X,ie10:Y,ie8:Ub,ie9:Vb,safari:hc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};GraphemeColour.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};GraphemeColour.__computePropValue=n;q.__gwt_activeModules[U].bindings=GraphemeColour.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([Nb,ac],kc);k([Nb,cc],lc);k([mc,ec],nc);k([mc,cc],oc);k([mc,gc],pc);k([qc,gc],rc);k([mc,ac],sc);k([mc,Yb],tc);k([Nb,gc],uc);k([Nb,Yb],vc);k([wc,gc],xc);k([qc,ec],yc);k([qc,cc],zc);k([wc,ac],Ac);k([Nb,ec],Bc);k([wc,Yb],Cc);k([qc,ac],Dc);k([qc,Yb],Ec);k([wc,ec],Fc);k([wc,cc],Gc);o=i[n(Mb)][n(Wb)];var p=o.indexOf(Hc);if(p!=-1){j=parseInt(o.substring(p+Y),$b);o=o.substring(X,p)}}catch(a){}GraphemeColour.__softPermutationId=j;return G(o+Ic)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Jc);b.setAttribute(Kc,Lc);b.setAttribute(Mc,G(a));r.getElementsByTagName(qb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Nc,R);c(Oc);t(Nc,Pc)}
D();GraphemeColour.__moduleBase=F();v[U].moduleBase=GraphemeColour.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Qc||q.location.protocol==Rc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Sc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Tc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Uc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+Vc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Pc);C(J);return true}
GraphemeColour.succeeded=GraphemeColour();